//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Barrio
    {
        public Barrio()
        {
            this.Incidentes = new HashSet<Incidente>();
            this.Direcciones = new HashSet<Direccion>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre ingresado no es valido")]
        [StringLength(50, ErrorMessage = "Ingrese hasta 50 caracteres") ]

        [Display(Name = "Barrio")]
        public string nombre { get; set; }

        [Display(Name = "Codigo Postal")]
        [Required(ErrorMessage = "El codigo ingresado no es valido")]

        [DataType(DataType.PostalCode)]
        public string codigoPostal { get; set; }

        [Display(Name = "Localidad")]
        [Required(ErrorMessage = "Debe seleccionar una Localidad")]
        public int localidadId { get; set; }

        [Display(Name = "Zona")]
        [Required(ErrorMessage = "Debe seleccionar una Zona")]
        public string Zona { get; set; }
    
        public virtual ICollection<Incidente> Incidentes { get; set; }
        public virtual Localidad Localidade { get; set; }
        public virtual ICollection<Direccion> Direcciones { get; set; }
    }
}
