//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePath
    {
        public int FilePathId { get; set; }
        public string FileName { get; set; }
        public int FileType { get; set; }
        public int animalId { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
