//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Provincias = new HashSet<Provincia>();
            this.Direcciones = new HashSet<Direccion>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Debe Ingresar un nombre de Pais")]
        [StringLength(50, ErrorMessage = "Ingrese hasta 50 caracteres")]

        [Display(Name = "Pais")]
        public string pais_nombre { get; set; }

         [Display(Name = "Habilitado")]
         public string pais_habil { get; set; }
         public virtual ICollection<Provincia> Provincias { get; set; }
         public virtual ICollection<Direccion> Direcciones { get; set; }
    }
}
