//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Adopcions = new HashSet<Adopcion>();
            this.Adopcions1 = new HashSet<Adopcion>();
            this.Apadrinamientoes = new HashSet<Apadrinamiento>();
            this.Apadrinamientoes1 = new HashSet<Apadrinamiento>();
            this.Direcciones = new HashSet<Direccion>();
            this.Incidentes = new HashSet<Incidente>();
            this.RegistroAcciones = new HashSet<RegistroAccione>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Ingrese un Nombre")]
        [StringLength(15, ErrorMessage = "Ingrese hasta 15 caracteres")]

        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Ingrese una Apellido")]
        [StringLength(15, ErrorMessage = "Ingrese hasta 15 caracteres")]

        [Display(Name = "Apellido")]
        public string Apellido { get; set; }

        [Required(ErrorMessage = "Ingrese la Fecha de Nacimiento")]
        [Display(Name = "Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        public DateTime fechaNac { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }

        [RegularExpression(@"((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}", ErrorMessage = "Nro invalido!")]
        [Display(Name = "Telefono")]

        public string telefono { get; set; }

        [RegularExpression(@"((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}", ErrorMessage = "Nro invalido!")]
        [Display(Name = "Celular")]
        public string telefonoCel { get; set; }

        [Display(Name = "Puntaje")]
        public Nullable<int> puntaje { get; set; }
        public string UsrId { get; set; }

        [Required(ErrorMessage = "Por favor ingrese su direccion e-mail.")]
        [RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$", ErrorMessage = "Invalid email format.")]
        [Display(Name = "eMail")]
        public string email { get; set; }

        [Display(Name = "Habilitado")]
        public bool estadohab { get; set; }

        [Display(Name = "Voluntario")]
        public bool voluntario { get; set; }
    
        public virtual ICollection<Adopcion> Adopcions { get; set; }
        public virtual ICollection<Adopcion> Adopcions1 { get; set; }
        public virtual ICollection<Apadrinamiento> Apadrinamientoes { get; set; }
        public virtual ICollection<Apadrinamiento> Apadrinamientoes1 { get; set; }
        public virtual ICollection<Direccion> Direcciones { get; set; }
        public virtual ICollection<Incidente> Incidentes { get; set; }
        public virtual ICollection<RegistroAccione> RegistroAcciones { get; set; }
    }
}
