//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProductoVeterinaria
    {
        public ProductoVeterinaria()
        {
            this.AtencionMedicas = new HashSet<AtencionMedica>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre del producto")]
        [StringLength(50, ErrorMessage = "Ingrese hasta 50 caracteres")]

        [Display(Name = "Producto")]
        public string nombre { get; set; }

        [Display(Name = "Cantidad")]
        [Range(0, 1000, ErrorMessage = "Ingrese un numero menor")]
        public Nullable<int> cantidad { get; set; }

        [Required(ErrorMessage = "Ingrese una descripcion")]
        [StringLength(50, ErrorMessage = "Ingrese hasta 50 caracteres")]
        [Display(Name = "Descripcion")]

         public string descripcion { get; set; }
        [Display(Name = "Baja")]
        public Nullable<System.DateTime> fechaBaja { get; set; }
    
        public virtual ICollection<AtencionMedica> AtencionMedicas { get; set; }
    }
}
