//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Localidades = new HashSet<Localidad>();
            this.Direcciones = new HashSet<Direccion>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Debe ingresar un nombre para Provincia")]
        [StringLength(50, ErrorMessage = "Ingrese hasta 50 caracteres")]

        [Display(Name = "Provincia")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Debe seleccionar un Pais")]
        [Display(Name = "Pais")]
        public Nullable<int> paisId { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Localidad> Localidades { get; set; }
        public virtual ICollection<Direccion> Direcciones { get; set; }
    }
}
