//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; 
    
    public partial class RegistroAccione
    {
        public int Id { get; set; }

        [Display(Name = "Fecha Alta")]
        public System.DateTime fechaAlta { get; set; }

        [Display(Name = "Fecha Baja")]
        public Nullable<System.DateTime> fechcaBaja { get; set; }

        [Display(Name = "Comentario")]
        public string comentario { get; set; }

        [Display(Name = "Persona")]
        public int personaId { get; set; }

        [Display(Name = "Accion")]
        public int accionesId { get; set; }

        [Display(Name = "Habilitado")]
        public bool estadoHab { get; set; }
        
    
        public virtual Accione Accione { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
