//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Veterinaria
    {
        public Veterinaria()
        {
            this.AtencionMedicas = new HashSet<AtencionMedica>();
            this.Direcciones = new HashSet<Direccion>();
        }
    
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Ingrese la denominacion de la Veterinaria")]
        [StringLength(50, ErrorMessage = "Ingrese hasta 50 caracteres")]

        [Display(Name = "Veterinaria")]
        public string nombre { get; set; }

        [Display(Name = "Direccion")]
        public string direccion { get; set; }

        [RegularExpression(@"((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}", ErrorMessage = "Nro invalido!")]
        [Display(Name = "Telefono")]

        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }

        public virtual ICollection<AtencionMedica> AtencionMedicas { get; set; }
        public virtual ICollection<Direccion> Direcciones { get; set; }
    }
}
