//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apadrinamiento
    {
        public int Id { get; set; }
        public Nullable<int> empleadoId { get; set; }
        public Nullable<int> voluntarioId { get; set; }
        public int animalId { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public System.DateTime fechaCancelacion { get; set; }
        public System.DateTime fechaConfirmacion { get; set; }
        public System.DateTime fechaBaja { get; set; }
        public float importe { get; set; }
        public int estadoApadrinamientoId { get; set; }
    
        public virtual EstadoApadrinamiento EstadoApadrinamiento { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual Animal Animal { get; set; }
    }
}
