//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtencionMedica
    {
        public int Id { get; set; }
        public int animalId { get; set; }
        public int veterinariaId { get; set; }
        public Nullable<int> productoVeterinariaId { get; set; }
        public string tratamiento { get; set; }
        public string nombreVeterinario { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
    
        public virtual ProductoVeterinaria ProductoVeterinaria { get; set; }
        public virtual Veterinaria Veterinaria { get; set; }
        public virtual Animal Animal { get; set; }
    }
}
