//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Calle
    {
        public Calle()
        {
            this.Direcciones = new HashSet<Direccion>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Debe Ingresar un nombre de Calle")]
        [StringLength(50, ErrorMessage = "Ingrese hasta 50 caracteres")]

        [Display(Name = "Calle")]
        public string calle_nombre { get; set; }
        public int localidadId { get; set; }
    
        public virtual ICollection<Direccion> Direcciones { get; set; }
        public virtual Localidad Localidade { get; set; }
    }
}
