//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int Id { get; set; }
        public int paisId { get; set; }
        public int provinciaId { get; set; }
        public int localidadId { get; set; }
        public int barrioId { get; set; }
        public int calleId { get; set; }
        public string piso { get; set; }
        public string Torre { get; set; }
        public string depto { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> personaId { get; set; }
        public Nullable<int> veterinariaId { get; set; }
        public Nullable<int> incidenteId { get; set; }
    
        public virtual Barrio Barrio { get; set; }
        public virtual Calle Calle { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Incidente Incidente { get; set; }
        public virtual Veterinaria Veterinaria { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
