//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FecParam
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
    }
}
