//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;


    public partial class Incidente
    {
        public Incidente()
        {
            this.Files = new HashSet<File>();
            this.Direcciones = new HashSet<Direccion>();
        }

    
        public int Id { get; set; }
        public string Email { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tamanioId { get; set; }
        public Nullable<int> razaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> tipoIncidenteId { get; set; }
        public Nullable<int> especieId { get; set; }
        public Nullable<int> estadoIncidenteId { get; set; }
        public string VoluntarioUsrId { get; set; }
        public string voluntarioName { get; set; }
        public Nullable<int> voluntarioId { get; set; }
        public string calle { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string VoluntarioSolucionUsrId { get; set; }
        public string voluntarioSolucionName { get; set; }
        public Nullable<int> barrioId { get; set; }
    
        public virtual Barrio Barrio { get; set; }
        public virtual EstadoIncidente EstadoIncidente { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Raza Raza { get; set; }
        public virtual Tamanio Tamanio { get; set; }
        public virtual TipoIncidente TipoIncidente { get; set; }
        public virtual ICollection<Direccion> Direcciones { get; set; }
    }
}
