//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpAer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAccione
    {
        public int Id { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechcaBaja { get; set; }
        public string comentario { get; set; }
        public int personaId { get; set; }
        public int accionesId { get; set; }
    
        public virtual Accione Accione { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
